services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: '172.29.8.249'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.29.8.249:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:2424'
    volumes:
      - '${PWD}/.gitlab/config:/etc/gitlab'
      - '${PWD}/.gitlab/logs:/var/log/gitlab'
      - '${PWD}/.gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
        rbp-test:
            aliases:
            - gitlab

  gitlab-runner-01:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-01
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${PWD}/.gitlab-runner/config:/etc/gitlab-runner'
    entrypoint: /bin/sh -c
    # command: >
    #   "gitlab-runner register
    #   --non-interactive
    #   --url 'http://172.29.159.180:8929'
    #   --token 'glrt-8YRrw_s6X1WTgLP--rtC'
    #   --executor 'docker'
    #   --docker-image 'alpine:latest'
    #   --description 'gitlab-runner-01'"    
    networks:
        rbp-test:
            aliases:
            - gitlab-runner  

networks:
  rbp-test:
    external: true
