stages:
  - lint
  - unit_test
  - integration_test

image: python:3

cache:
  paths:
    - .pipenv_cache/
    - .venv/
    - /usr/lib/jvm/

before_script:
  - apt-get update
  - echo "*** Installing Python requirements ***"
  - python3 --version
  - echo "Upgrading pip"
  - pip install --upgrade pip
  - pip install pipenv
  - echo "Clearing pipenv cache"
  - pipenv run pipenv-resolver --clear || true
  - echo "Installing Python dependencies"
  - pipenv install -r requirements.txt
  - echo "Setting PYTHONPATH"
  - export PYTHONPATH=$PWD
  - echo "*** Finish installing Python requirements ***"
  - echo "*** Installing Java ***"
  - apt-get install default-jre default-jdk -y
  - java -version

lint:
  stage: lint
  script:
    - echo "Linting code... This will take about 10 seconds."
    - pipenv run pre-commit run --all-files

unit_test:
  stage: unit_test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - pipenv run unittest discover unittests

integration_test:
  stage: integration_test
  script:
    - echo "Running integration tests..."
    - pipenv run pytest booker_api/rooms/test_rooms.py booker_api/bookings/test_bookings.py booker_api/brandings/test_brandings.py booker_api/messages/test_messages.py booker_api/reports/test_reports.py -v -s
    - echo "Integration tests executed successfully."
