services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto_framework
    container_name: api_automation_2024_b-app-1
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1  # Desactiva el búfer de salida para mostrar los logs inmediatamente
    command: bash
    ports:
      - "9999:9999"
    networks:
        rbp-test:
            aliases:
            - app

networks:
    rbp-test:
        external: true
