version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_container
    ports:
      - "8082:8080"  # Cambiado el puerto del host de 8080 a 8081
      - "50001:50000"  # Cambiado el puerto del host de 50000 a 50001
    restart: always
    volumes:
      - ${PWD}/.jenkins_data:/var/jenkins_home
    networks:
      - jenkins_network

  rbp-booking:
    image: mwinteringham/restfulbookerplatform_booking:1.6.a1fd0e5
    ports:
      - "3000:3000"
    restart: always
    networks:
      - jenkins_network

  rbp-room:
    image: mwinteringham/restfulbookerplatform_room:1.6.a1fd0e5
    ports:
      - "3001:3001"
    restart: always
    networks:
      - jenkins_network

  rbp-branding:
    image: mwinteringham/restfulbookerplatform_branding:1.6.a1fd0e5
    ports:
      - "3002:3002"
    restart: always
    networks:
      - jenkins_network

  rbp-assets:
    image: mwinteringham/restfulbookerplatform_assets:1.6.a1fd0e5
    ports:
      - "3003:3003"
    restart: always
    networks:
      - jenkins_network

  rbp-auth:
    image: mwinteringham/restfulbookerplatform_auth:1.6.a1fd0e5
    ports:
      - "3004:3004"
    restart: always
    networks:
      - jenkins_network

  rbp-report:
    image: mwinteringham/restfulbookerplatform_report:1.6.a1fd0e5
    ports:
      - "3005:3005"
    restart: always
    networks:
      - jenkins_network

  rbp-message:
    image: mwinteringham/restfulbookerplatform_message:1.6.a1fd0e5
    ports:
      - "3006:3006"
    restart: always
    networks:
      - jenkins_network

  rbp-proxy:
    image: mwinteringham/restfulbookerplatform_proxy:latest
    ports:
      - "8080:80"
    restart: always
    networks:
      - jenkins_network

networks:
  jenkins_network:
