services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_container
    privileged: true
    user: root
    restart: always
    ports:
      - "8082:8080"  # Cambiado el puerto del host de 8080 a 8081
      - "50001:50000"  # Cambiado el puerto del host de 50000 a 50001
    volumes:
      - ${PWD}/.jenkins_data:/var/jenkins_home
    networks:
        rbp-test:
            aliases:
            - jenkins  

networks:
    rbp-test:
        external: true